import { Template } from 'meteor/templating';

import './body.html';

Template.body.helpers ({
    cars: [
        {
            "body": "Седан",
            "comment": "",
            "mileage": "140500",
            "color": "Серебристый",
            "price": "230000",
            "steering_wheel": "Левый",
            "volume": "2.2 (л)",
            "transmission": "Автомат",
            "wheel_drive": "Передний",
            "location": "Бишкек/Чуй обл.",
            "doors": "4/5",
            "year": "1999",
            "images": ["http://static.akipress.org/img/auto2.0/blank_images/photononb.jpg"],
            "uniq": "http://auto.doska.kg/auto:99260/?category=3&order=date_new",
            "model": "Прочие",
            "scrapy-mongodb": {"ts": "2016-08-29T04:58:39.480000"},
            "fuel_type": "Бензин",
            "make": "Toyota"
        },
        {
            "body": "Внедорожник",
            "comment": "Описывать все характеристики не имеет смысла. Все стандартно. ",
            "mileage": "",
            "color": "Серый",
            "price": "25000",
            "steering_wheel": "Левый",
            "volume": "4.664 (л)",
            "transmission": "Автомат",
            "wheel_drive": "4х4/AWD",
            "location": "Бишкек/Чуй обл.",
            "doors": "4/5",
            "year": "2007",
            "images": [
                "http://auto.static.akipress.org/213/399669-1.1.jpg",
                "http://auto.static.akipress.org/213/399670-1.1.jpg",
                "http://auto.static.akipress.org/213/399671-1.1.jpg",
                "http://auto.static.akipress.org/213/399672-1.1.jpg",
                "http://auto.static.akipress.org/213/399673-1.1.jpg",
                "http://auto.static.akipress.org/213/399674-1.1.jpg",
                "http://auto.static.akipress.org/213/399675-1.1.jpg",
                "http://auto.static.akipress.org/213/399676-1.1.jpg",
                "http://auto.static.akipress.org/213/399668-1.1.jpg"
            ],
            "uniq": "http://auto.doska.kg/auto:99213/?category=3&order=date_new",
            "model": "GX 470",
            "scrapy-mongodb": {"ts": "2016-08-29T04:58:23.120000"},
            "fuel_type": "Бензин",
            "make": "Lexus"
        },
        {
            "body": "Купе",
            "comment": "состояния средний  фото через ватсап",
            "mileage": "",
            "color": "другой",
            "price": "45000",
            "steering_wheel": "Левый",
            "volume": "2 (л)",
            "transmission": "Механика",
            "wheel_drive": "Передний",
            "location": "Бишкек/Чуй обл.",
            "doors": "2/3",
            "year": "1984",
            "images": ["http://static.akipress.org/img/auto2.0/blank_images/photononb.jpg"],
            "uniq": "http://auto.doska.kg/auto:99186/?category=3&order=date_new",
            "model": "626",
            "scrapy-mongodb": {"ts": "2016-08-26T10:21:15.331000"},
            "fuel_type": "Бензин",
            "make": "Mazda"
        },
        {
            "body": "Хетчбек",
            "comment": "Аукцион 3В нужно заменить масло в двигателе.",
            "mileage": "51000",
            "color": "Серебристый",
            "price": "3800",
            "steering_wheel": "ПРАВЫЙ",
            "volume": "1.3 (л)",
            "transmission": "Вариатор",
            "wheel_drive": "Передний",
            "location": "Бишкек/Чуй обл.",
            "doors": "4/5",
            "year": "2004",
            "images": ["http://auto.static.akipress.org/189/399513-1.1.jpg"],
            "uniq": "http://auto.doska.kg/auto:99189/?category=3&order=date_new",
            "model": "FIT",
            "scrapy-mongodb": {"ts": "2016-08-29T04:57:48.605000"},
            "fuel_type": "Бензин",
            "make": "Honda"
        }
        ,
        {
            "body": "Внедорожник",
            "comment": "Прекрасный подарок для юбиляров. Идеальное состояние+ навороты+ красивый 4-х значный номер.",
            "mileage": "",
            "color": "Черный",
            "price": "12990000",
            "steering_wheel": "Левый",
            "volume": "3.5 (л)",
            "transmission": "Автомат",
            "wheel_drive": "4х4/AWD",
            "location": "Бишкек/Чуй обл.",
            "doors": "4/5",
            "year": "2007",
            "images": [
                "http://auto.static.akipress.org/256/400041-1.1.jpg",
                "http://auto.static.akipress.org/256/400042-1.1.jpg",
                "http://auto.static.akipress.org/256/400043-1.1.jpg",
                "http://auto.static.akipress.org/256/400044-1.1.jpg",
                "http://auto.static.akipress.org/256/400040-1.1.jpg"
            ],
            "uniq": "http://auto.doska.kg/auto:99256/?category=3&order=date_new",
            "model": "M klasse (W164)",
            "scrapy-mongodb": {"ts": "2016-08-29T04:59:03.881000"},
            "fuel_type": "Бензин",
            "make": "Mercedes-Benz"
        },
        {
            "body": "Универсал",
            "comment": "",
            "mileage": "",
            "color": "Черный",
            "price": "515980",
            "steering_wheel": "Левый",
            "volume": "2.5 (л)",
            "transmission": "Автомат",
            "wheel_drive": "4х4/AWD",
            "location": "Бишкек/Чуй обл.",
            "doors": "4/5",
            "year": "2005",
            "images": ["http://static.akipress.org/img/auto2.0/blank_images/photononb.jpg"],
            "uniq": "http://auto.doska.kg/auto:99290/?category=3&order=date_new",
            "model": "Outback",
            "scrapy-mongodb": {"ts": "2016-08-29T04:57:00.469000"},
            "fuel_type": "Бензин",
            "make": "Subaru"
        },
        {
            "body": "Универсал",
            "comment": "или обмен с доплатой мне",
            "mileage": "",
            "color": "Серебристый",
            "price": "600000",
            "steering_wheel": "Левый",
            "volume": "2.5 (л)",
            "transmission": "Автомат",
            "wheel_drive": "4х4/AWD",
            "location": "Бишкек/Чуй обл.",
            "doors": "4/5",
            "year": "2006",
            "images": ["http://static.akipress.org/img/auto2.0/blank_images/photononb.jpg"],
            "uniq": "http://auto.doska.kg/auto:99277/?category=3&order=date_new",
            "model": "Outback",
            "scrapy-mongodb": {"ts": "2016-08-29T04:57:00.465000"},
            "fuel_type": "Бензин",
            "make": "Subaru"
        },
        {
            "body": "Внедорожник",
            "comment": "Отличное состояние",
            "mileage": "170000",
            "color": "Серебристый",
            "price": "1104000",
            "steering_wheel": "Левый",
            "volume": "4.7 (л)",
            "transmission": "Автомат",
            "wheel_drive": "4х4/AWD",
            "location": "Бишкек/Чуй обл.",
            "doors": "4/5",
            "year": "2004",
            "images": ["http://static.akipress.org/img/auto2.0/blank_images/photononb.jpg"],
            "uniq": "http://auto.doska.kg/auto:99281/?category=3&order=date_new",
            "model": "GX 470",
            "scrapy-mongodb": {"ts": "2016-08-29T04:57:01.262000"},
            "fuel_type": "Бензин",
            "make": "Lexus"
        },
        {
            "body": "Хетчбек",
            "comment": "Срочно продам для Toyota Venza 2015 модель, авария бесплатно Auto первого тела. Отличное состояние со всеми всесезонных шин, не имеет повреждений и имеет один владелец.",
            "mileage": "33575",
            "color": "Красный",
            "price": "940000",
            "steering_wheel": "Левый",
            "volume": "2.7 (л)",
            "transmission": "Автомат",
            "wheel_drive": "4х4/AWD",
            "location": "Бишкек/Чуй обл.",
            "doors": "4/5",
            "year": "2015",
            "images": [
                "http://auto.static.akipress.org/273/400112-87707985.1.jpg",
                "http://auto.static.akipress.org/273/400113-87707985.1.jpg",
                "http://auto.static.akipress.org/273/400114-87707985.1.jpg",
                "http://auto.static.akipress.org/273/400115-87707985.1.jpg",
                "http://auto.static.akipress.org/273/400116-87707985.1.jpg",
                "http://auto.static.akipress.org/273/400111-87707985.1.jpg"
            ],
            "uniq": "http://auto.doska.kg/auto:99273/?category=3&order=date_new",
            "model": "Avalon",
            "scrapy-mongodb": {"ts": "2016-08-29T04:57:14.099000"},
            "fuel_type": "Бензин",
            "make": "Toyota"
        },
        {
            "body": "Хетчбек",
            "comment": "Машина в отличном состоянии, без вложений сел и поехал, Opel astra G 2000 года, цвет  серебро, мотор экотек 1.6 , недавно поставил газ евро 4 итальянское номера таджикские. пишите viber",
            "mileage": "",
            "color": "Серебристый",
            "price": "320000",
            "steering_wheel": "ПРАВЫЙ",
            "volume": "1.6 (л)",
            "transmission": "Механика",
            "wheel_drive": "Передний",
            "location": "Баткенская обл.",
            "doors": "4/5",
            "year": "2000",
            "images": [
                "http://auto.static.akipress.org/265/400090-1.1.jpg",
                "http://auto.static.akipress.org/265/400091-1.1.jpg",
                "http://auto.static.akipress.org/265/400089-1.1.jpg"
            ],
            "uniq": "http://auto.doska.kg/auto:99265/?category=3&order=date_new",
            "model": "Astra",
            "scrapy-mongodb": {"ts": "2016-08-29T05:00:08.601000"},
            "fuel_type": "Бензин/Газ",
            "make": "Opel"
        }
    ]
});